---
- hosts: webservers
  tasks:
    - name: instaleerime php7.0
      apt: name=php7.0 update_cache=yes state=latest
    - name: instaleerime libapache2-mod-php7.0
      apt: name=libapache2-mod-php7.0 update_cache=yes state=latest
    - name: instaleerime php7.0-mysql
      apt: name=php7.0-mysql update_cache=yes state=latest

    - name: Apache restart
      service:
        name: apache2
        state: restarted
